import React from 'react';

export default function Ethics() {
  return (
    <div className="glass-panel" style={{ maxWidth: '800px', margin: '0 auto', borderLeft: '4px solid var(--secondary)' }}>
      <h2 style={{ fontFamily: 'var(--font-display)', color: 'var(--secondary)', marginBottom: '1.5rem' }}>// ETHICS_PROTOCOL</h2>
      
      <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', fontFamily: 'var(--font-body)', color: 'var(--text)' }}>
        <section>
          <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '0.9rem', color: 'var(--primary)', marginBottom: '0.5rem' }}>01. AI LIMITATIONS</h3>
          <p style={{ fontSize: '0.9rem' }}>Sentinel AI models are probabilistic, not deterministic. Intelligence bypasses may occasionally result in hallucinations or factual inaccuracies. Always cross-verify critical data with human intelligence (HUMINT).</p>
        </section>

        <section>
          <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '0.9rem', color: 'var(--primary)', marginBottom: '0.5rem' }}>02. BIAS IN ANALYSIS</h3>
          <p style={{ fontSize: '0.9rem' }}>Our neural networks are trained on large-scale datasets that may contain inherent sociopolitical biases. The system aims for neutrality but must be audited regularly for pattern-matching anomalies.</p>
        </section>

        <section>
          <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '0.9rem', color: 'var(--primary)', marginBottom: '0.5rem' }}>03. RESPONSIBILITY</h3>
          <p style={{ fontSize: '0.9rem' }}>The user assumes all tactical risks associated with the deployment of results generated by this tool. FakeShield is a supportive analysis asset, not a substitute for critical investigative thinking.</p>
        </section>

        <section>
          <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '0.9rem', color: 'var(--primary)', marginBottom: '0.5rem' }}>04. PRIVACY & DATA</h3>
          <p style={{ fontSize: '0.9rem' }}>Analyzed content is transmitted via secure channels to the Groq intelligence core. We do not store original article content in the knowledge base without explicit authorization.</p>
        </section>

        <section>
          <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '0.9rem', color: 'var(--primary)', marginBottom: '0.5rem' }}>05. TRANSPARENCY</h3>
          <p style={{ fontSize: '0.9rem' }}>Logical reasoning steps (REASON 1-3) are provided for every analysis to ensure full transparency of the AI decision-making process.</p>
        </section>
      </div>
    </div>
  );
}
